
name: site - Challenge 1

# Le workflow se déclenchera quand on fera un git push sur main
on:
  push:
    branches:
      - main

jobs:
  cowsay-job:
    runs-on: ubuntu-latest

    steps:
      # Étape pour afficher une vache avec cowsay
      - name: deploy site
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
          cowsay "Hello from GitHub Actions!"
          echo "DONE"
